name             'certificate'
source_url       'https://github.com/sous-chefs/certificate'
issues_url       'https://github.com/sous-chefs/certificate/issues'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
chef_version     '>= 15.3'
license          'Apache-2.0'
description      'Installs and configures certificates, private keys, CA root bundles from encrypted data bags.'
version          '2.0.17'

supports 'amazon'
supports 'arch'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'freebsd'
supports 'opensuse'
supports 'opensuseleap'
supports 'redhat'
supports 'scientific'
supports 'suse'
supports 'ubuntu'
