name             'certificate'
source_url       'https://github.com/sous-chefs/certificate'
issues_url       'https://github.com/sous-chefs/certificate/issues'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
chef_version     '>= 16'
license          'Apache-2.0'
description      'Installs and configures certificates, private keys, CA root bundles from encrypted data bags.'
version          '2.1.4'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos-stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'
