name             'certificate'
source_url       'https://github.com/sous-chefs/certificate'
issues_url       'https://github.com/sous-chefs/certificate/issues'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
chef_version     '>= 15.3'
license          'Apache-2.0'
description      'Installs and configures certificates, private keys, CA root bundles from data bags.'
version          '3.0.0'

supports 'almalinux'
supports 'amazon'
supports 'debian'
supports 'freebsd'
supports 'opensuse'
supports 'opensuseleap'
supports 'redhat'
supports 'rocky'
supports 'suse'
supports 'ubuntu'
